version: '3'

services:
  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: qwerty123
      MYSQL_DATABASE: facdb
    volumes:
      -  ./data:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"
    command: --default-authentication-plugin=mysql_native_password
    user: "1000:1000"
    restart: always
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      FLASK_APP: app.py
      FLASK_ENV: development
    depends_on:
      - db

    restart: always